# Generated by Django 5.1.1 on 2024-10-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productsApi", "0002_category_order_orderitem_product_review_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
