# Generated by Django 5.1.1 on 2024-10-04 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productsApi", "0003_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
